// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/wishlist.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item_ItemPriority int32

const (
	Item_LOW  Item_ItemPriority = 0
	Item_MID  Item_ItemPriority = 50
	Item_HIGH Item_ItemPriority = 100
)

var Item_ItemPriority_name = map[int32]string{
	0:   "LOW",
	50:  "MID",
	100: "HIGH",
}

var Item_ItemPriority_value = map[string]int32{
	"LOW":  0,
	"MID":  50,
	"HIGH": 100,
}

func (x Item_ItemPriority) String() string {
	return proto.EnumName(Item_ItemPriority_name, int32(x))
}

func (Item_ItemPriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{0, 0}
}

type Item_ItemStatus int32

const (
	Item_INACTIVE Item_ItemStatus = 0
	Item_ACTIVE   Item_ItemStatus = 1
)

var Item_ItemStatus_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
}

var Item_ItemStatus_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
}

func (x Item_ItemStatus) String() string {
	return proto.EnumName(Item_ItemStatus_name, int32(x))
}

func (Item_ItemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{0, 1}
}

type WishList_WishListStatus int32

const (
	WishList_INACTIVE WishList_WishListStatus = 0
	WishList_ACTIVE   WishList_WishListStatus = 1
)

var WishList_WishListStatus_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
}

var WishList_WishListStatus_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
}

func (x WishList_WishListStatus) String() string {
	return proto.EnumName(WishList_WishListStatus_name, int32(x))
}

func (WishList_WishListStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{1, 0}
}

type Item struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WishListId           string            `protobuf:"bytes,2,opt,name=wishListId,proto3" json:"wishListId,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Link                 string            `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Price                float64           `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Priority             Item_ItemPriority `protobuf:"varint,6,opt,name=priority,proto3,enum=grpc.Item_ItemPriority" json:"priority,omitempty"`
	Status               Item_ItemStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=grpc.Item_ItemStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetWishListId() string {
	if m != nil {
		return m.WishListId
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Item) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetPriority() Item_ItemPriority {
	if m != nil {
		return m.Priority
	}
	return Item_LOW
}

func (m *Item) GetStatus() Item_ItemStatus {
	if m != nil {
		return m.Status
	}
	return Item_INACTIVE
}

type WishList struct {
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               WishList_WishListStatus `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.WishList_WishListStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WishList) Reset()         { *m = WishList{} }
func (m *WishList) String() string { return proto.CompactTextString(m) }
func (*WishList) ProtoMessage()    {}
func (*WishList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{1}
}

func (m *WishList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WishList.Unmarshal(m, b)
}
func (m *WishList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WishList.Marshal(b, m, deterministic)
}
func (m *WishList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WishList.Merge(m, src)
}
func (m *WishList) XXX_Size() int {
	return xxx_messageInfo_WishList.Size(m)
}
func (m *WishList) XXX_DiscardUnknown() {
	xxx_messageInfo_WishList.DiscardUnknown(m)
}

var xxx_messageInfo_WishList proto.InternalMessageInfo

func (m *WishList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WishList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WishList) GetStatus() WishList_WishListStatus {
	if m != nil {
		return m.Status
	}
	return WishList_INACTIVE
}

type CreateWishListReq struct {
	WishList             *WishList `protobuf:"bytes,1,opt,name=wishList,proto3" json:"wishList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateWishListReq) Reset()         { *m = CreateWishListReq{} }
func (m *CreateWishListReq) String() string { return proto.CompactTextString(m) }
func (*CreateWishListReq) ProtoMessage()    {}
func (*CreateWishListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{2}
}

func (m *CreateWishListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWishListReq.Unmarshal(m, b)
}
func (m *CreateWishListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWishListReq.Marshal(b, m, deterministic)
}
func (m *CreateWishListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWishListReq.Merge(m, src)
}
func (m *CreateWishListReq) XXX_Size() int {
	return xxx_messageInfo_CreateWishListReq.Size(m)
}
func (m *CreateWishListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWishListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWishListReq proto.InternalMessageInfo

func (m *CreateWishListReq) GetWishList() *WishList {
	if m != nil {
		return m.WishList
	}
	return nil
}

type CreateWishListResp struct {
	WishListId           string   `protobuf:"bytes,1,opt,name=wishListId,proto3" json:"wishListId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWishListResp) Reset()         { *m = CreateWishListResp{} }
func (m *CreateWishListResp) String() string { return proto.CompactTextString(m) }
func (*CreateWishListResp) ProtoMessage()    {}
func (*CreateWishListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{3}
}

func (m *CreateWishListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWishListResp.Unmarshal(m, b)
}
func (m *CreateWishListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWishListResp.Marshal(b, m, deterministic)
}
func (m *CreateWishListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWishListResp.Merge(m, src)
}
func (m *CreateWishListResp) XXX_Size() int {
	return xxx_messageInfo_CreateWishListResp.Size(m)
}
func (m *CreateWishListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWishListResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWishListResp proto.InternalMessageInfo

func (m *CreateWishListResp) GetWishListId() string {
	if m != nil {
		return m.WishListId
	}
	return ""
}

type AddItemReq struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemReq) Reset()         { *m = AddItemReq{} }
func (m *AddItemReq) String() string { return proto.CompactTextString(m) }
func (*AddItemReq) ProtoMessage()    {}
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{4}
}

func (m *AddItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemReq.Unmarshal(m, b)
}
func (m *AddItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemReq.Marshal(b, m, deterministic)
}
func (m *AddItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemReq.Merge(m, src)
}
func (m *AddItemReq) XXX_Size() int {
	return xxx_messageInfo_AddItemReq.Size(m)
}
func (m *AddItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemReq proto.InternalMessageInfo

func (m *AddItemReq) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type AddItemResp struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemResp) Reset()         { *m = AddItemResp{} }
func (m *AddItemResp) String() string { return proto.CompactTextString(m) }
func (*AddItemResp) ProtoMessage()    {}
func (*AddItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{5}
}

func (m *AddItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemResp.Unmarshal(m, b)
}
func (m *AddItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemResp.Marshal(b, m, deterministic)
}
func (m *AddItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemResp.Merge(m, src)
}
func (m *AddItemResp) XXX_Size() int {
	return xxx_messageInfo_AddItemResp.Size(m)
}
func (m *AddItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemResp proto.InternalMessageInfo

func (m *AddItemResp) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type ListWishListReq struct {
	WishListId           string   `protobuf:"bytes,1,opt,name=wishListId,proto3" json:"wishListId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWishListReq) Reset()         { *m = ListWishListReq{} }
func (m *ListWishListReq) String() string { return proto.CompactTextString(m) }
func (*ListWishListReq) ProtoMessage()    {}
func (*ListWishListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{6}
}

func (m *ListWishListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWishListReq.Unmarshal(m, b)
}
func (m *ListWishListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWishListReq.Marshal(b, m, deterministic)
}
func (m *ListWishListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWishListReq.Merge(m, src)
}
func (m *ListWishListReq) XXX_Size() int {
	return xxx_messageInfo_ListWishListReq.Size(m)
}
func (m *ListWishListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWishListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListWishListReq proto.InternalMessageInfo

func (m *ListWishListReq) GetWishListId() string {
	if m != nil {
		return m.WishListId
	}
	return ""
}

type ListWishListResp struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWishListResp) Reset()         { *m = ListWishListResp{} }
func (m *ListWishListResp) String() string { return proto.CompactTextString(m) }
func (*ListWishListResp) ProtoMessage()    {}
func (*ListWishListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fed595f0d2823e2c, []int{7}
}

func (m *ListWishListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWishListResp.Unmarshal(m, b)
}
func (m *ListWishListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWishListResp.Marshal(b, m, deterministic)
}
func (m *ListWishListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWishListResp.Merge(m, src)
}
func (m *ListWishListResp) XXX_Size() int {
	return xxx_messageInfo_ListWishListResp.Size(m)
}
func (m *ListWishListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWishListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListWishListResp proto.InternalMessageInfo

func (m *ListWishListResp) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("grpc.Item_ItemPriority", Item_ItemPriority_name, Item_ItemPriority_value)
	proto.RegisterEnum("grpc.Item_ItemStatus", Item_ItemStatus_name, Item_ItemStatus_value)
	proto.RegisterEnum("grpc.WishList_WishListStatus", WishList_WishListStatus_name, WishList_WishListStatus_value)
	proto.RegisterType((*Item)(nil), "grpc.Item")
	proto.RegisterType((*WishList)(nil), "grpc.WishList")
	proto.RegisterType((*CreateWishListReq)(nil), "grpc.CreateWishListReq")
	proto.RegisterType((*CreateWishListResp)(nil), "grpc.CreateWishListResp")
	proto.RegisterType((*AddItemReq)(nil), "grpc.AddItemReq")
	proto.RegisterType((*AddItemResp)(nil), "grpc.AddItemResp")
	proto.RegisterType((*ListWishListReq)(nil), "grpc.ListWishListReq")
	proto.RegisterType((*ListWishListResp)(nil), "grpc.ListWishListResp")
}

func init() { proto.RegisterFile("proto/wishlist.proto", fileDescriptor_fed595f0d2823e2c) }

var fileDescriptor_fed595f0d2823e2c = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x9d, 0x93, 0x34, 0x0b, 0x77, 0x53, 0x97, 0x5d, 0x8d, 0x61, 0x55, 0x62, 0x8a, 0x22, 0x81,
	0xaa, 0x6a, 0x6d, 0x45, 0xb7, 0x3d, 0xf1, 0x80, 0xca, 0x40, 0x2c, 0xd2, 0xf8, 0x50, 0x40, 0x4c,
	0xe2, 0xad, 0x6b, 0xac, 0xcd, 0xda, 0xb2, 0x98, 0xd8, 0x03, 0xf1, 0x33, 0xf8, 0x1f, 0xbc, 0xf0,
	0x0f, 0x91, 0x9d, 0x8f, 0xa6, 0x69, 0xc5, 0x5e, 0x92, 0xeb, 0x73, 0xef, 0x3d, 0x3e, 0x3e, 0xbe,
	0x86, 0x3d, 0x91, 0x67, 0x2a, 0x1b, 0xff, 0xe4, 0xf2, 0xfa, 0x96, 0x4b, 0x35, 0x32, 0x4b, 0x74,
	0xae, 0x72, 0x31, 0x0f, 0xff, 0x58, 0xe0, 0x44, 0x8a, 0xa5, 0xd8, 0x05, 0x8b, 0x27, 0x94, 0x04,
	0xa4, 0xff, 0x28, 0xb6, 0x78, 0x82, 0x07, 0x00, 0xba, 0xe1, 0x9c, 0x4b, 0x15, 0x25, 0xd4, 0x32,
	0x78, 0x03, 0x41, 0x04, 0xe7, 0x6e, 0x96, 0x32, 0x6a, 0x9b, 0x8c, 0x89, 0x35, 0x76, 0xcb, 0xef,
	0x6e, 0xa8, 0x53, 0x60, 0x3a, 0xc6, 0x3d, 0xe8, 0x88, 0x9c, 0xcf, 0x19, 0xed, 0x04, 0xa4, 0x4f,
	0xe2, 0x62, 0x81, 0x47, 0xe0, 0x89, 0x9c, 0x67, 0x39, 0x57, 0xbf, 0xa8, 0x1b, 0x90, 0x7e, 0x77,
	0xf2, 0x64, 0xa4, 0xf5, 0x8c, 0xb4, 0x16, 0xf3, 0xf9, 0x54, 0xa6, 0xe3, 0xba, 0x10, 0x87, 0xe0,
	0x4a, 0x35, 0x53, 0xf7, 0x92, 0x6e, 0x9a, 0x96, 0xc7, 0xad, 0x96, 0xcf, 0x26, 0x19, 0x97, 0x45,
	0xe1, 0x00, 0xb6, 0x9b, 0x44, 0xb8, 0x09, 0xf6, 0xf9, 0xc7, 0x0b, 0x7f, 0x43, 0x07, 0xef, 0xa3,
	0x37, 0xfe, 0x04, 0x3d, 0x70, 0xce, 0xa2, 0x77, 0x67, 0x7e, 0x12, 0x3e, 0x07, 0x58, 0x30, 0xe0,
	0x36, 0x78, 0xd1, 0x87, 0xe9, 0xe9, 0x97, 0xe8, 0xeb, 0x5b, 0x7f, 0x03, 0x01, 0xdc, 0x32, 0x26,
	0xe1, 0x6f, 0x02, 0xde, 0x45, 0x69, 0xc2, 0x8a, 0x65, 0x95, 0x25, 0x56, 0xc3, 0x92, 0x93, 0x5a,
	0xb3, 0x6d, 0x34, 0x3f, 0x2d, 0x34, 0x57, 0x1c, 0x75, 0xb0, 0xa2, 0xbd, 0xbb, 0x9c, 0xf9, 0x8f,
	0xa6, 0x57, 0xb0, 0x7b, 0x9a, 0xb3, 0x99, 0x62, 0x55, 0x47, 0xcc, 0xbe, 0xe3, 0x00, 0xbc, 0xea,
	0xb2, 0x8c, 0xc2, 0xad, 0x49, 0x77, 0x79, 0xe7, 0xb8, 0xce, 0x87, 0xc7, 0x80, 0x6d, 0x02, 0x29,
	0x5a, 0x03, 0x40, 0xda, 0x03, 0x10, 0x1e, 0x02, 0x4c, 0x93, 0x44, 0xbb, 0xa6, 0xf7, 0x3b, 0x00,
	0x87, 0x2b, 0x96, 0x96, 0x7b, 0xc1, 0xe2, 0x66, 0x62, 0x83, 0x87, 0xcf, 0x60, 0xab, 0xae, 0x96,
	0x02, 0xf7, 0xc1, 0xd5, 0x70, 0x4d, 0x5c, 0xae, 0xc2, 0x17, 0xb0, 0xa3, 0xe9, 0x9b, 0x27, 0x79,
	0x48, 0xc7, 0x31, 0xf8, 0xcb, 0x2d, 0x52, 0x60, 0x00, 0x1d, 0x4d, 0x28, 0x29, 0x09, 0xec, 0x96,
	0x9c, 0x22, 0x31, 0xf9, 0x4b, 0x60, 0xa7, 0x76, 0x98, 0xe5, 0x3f, 0xf4, 0x50, 0xbe, 0x04, 0xb7,
	0xf0, 0x01, 0xcb, 0x61, 0x5c, 0xb1, 0xb5, 0x47, 0xd7, 0x27, 0xa4, 0xc0, 0x01, 0xd8, 0xd3, 0x24,
	0x41, 0xbf, 0x28, 0x58, 0x38, 0xd3, 0xdb, 0x6d, 0x21, 0x52, 0xe0, 0x09, 0x38, 0x66, 0x80, 0xca,
	0x01, 0x6e, 0x9d, 0xb8, 0xb7, 0xbf, 0x0e, 0x96, 0xe2, 0xf5, 0xe1, 0xb7, 0xc1, 0x15, 0x57, 0xd7,
	0xf7, 0x97, 0xa3, 0x79, 0x96, 0x8e, 0x55, 0x96, 0xf2, 0xec, 0x66, 0xac, 0x4b, 0x87, 0x8a, 0x49,
	0x35, 0xac, 0xde, 0xf7, 0xd8, 0xbc, 0xef, 0x4b, 0xd7, 0xfc, 0x8e, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xc3, 0xf2, 0xe6, 0xa4, 0xfe, 0x03, 0x00, 0x00,
}
